#############################################################################
# Makefile for building: TheSteambird
# Generated by qmake (3.1) (Qt 6.3.1)
# Project:  TheSteambird.pro
# Template: subdirs
# Command: D:\ruanjian\Qt\6.3.1\msvc2019_64\bin\qmake.exe -o Makefile TheSteambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\ruanjian\Qt\6.3.1\msvc2019_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\ruanjian\Qt\6.3.1\msvc2019_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\ruanjian\Qt\6.3.1\msvc2019_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-steambird


sub-steambird-qmake_all:  FORCE
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	cd steambird\ && $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && $(MAKE) -f Makefile qmake_all
sub-steambird: $(MAKEFILE) FORCE
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-steambird-make_first: FORCE
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-steambird-all: FORCE
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-steambird-clean: FORCE
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-steambird-distclean: FORCE
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-steambird-install_subtargets: FORCE
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-steambird-uninstall_subtargets: FORCE
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: TheSteambird.pro ..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf ..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\spec_pre.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\common\windows-desktop.conf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\common\windows-vulkan.conf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\common\msvc-desktop.conf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\qconfig.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_core.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_help.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_jsonrpc_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_languageserver_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_network.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdf.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdf_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdfquick.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdfquick_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmllint_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\qt_functions.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\qt_config.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\exclusive_builds.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\common\msvc-version.conf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\toolchain.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\default_pre.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\win32\default_pre.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\resolve_config.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\default_post.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\qml_debug.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\entrypoint.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\precompile_header.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\warn_on.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\qmake_use.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\file_copies.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\win32\windows.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\testcase_targets.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\exceptions.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\yacc.prf \
		..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\lex.prf \
		TheSteambird.pro
	$(QMAKE) -o Makefile TheSteambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\spec_pre.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\common\windows-desktop.conf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\win32\windows_vulkan_sdk.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\common\windows-vulkan.conf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\common\msvc-desktop.conf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\qconfig.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_ext_freetype.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_ext_libjpeg.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_ext_libpng.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_activeqt_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_bodymovin_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_charts.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_chartsqml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_core.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_core5compat.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_core5compat_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_datavisualizationqml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_designer.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_entrypoint_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_freetype_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_gui.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_harfbuzz_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_help.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_jpeg_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_jsonrpc_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsanimation_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsfolderlistmodel_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labsqmlmodels_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labssettings_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labssharedimage_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_labswavefrontmesh_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_languageserver_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_linguist.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_linguist_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimediaquick_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_network.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_openglwidgets_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdf.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdf_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdfquick.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdfquick_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_pdfwidgets_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_png_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcompiler_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlcore_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmldom_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlintegration_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmllint_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmllocalstorage_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_qmlxmllistmodel_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quick.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrols2impl_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickcontrolstestutilsprivate_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2quickimpl_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickdialogs2utils_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicklayouts_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktestutilsprivate_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quicktimeline_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_remoteobjectsqml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_scxmlqml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sensorsquick_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_shadertools.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_shadertools_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sql.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_statemachine.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_statemachine_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_statemachineqml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_svg.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_svgwidgets_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_tools_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_virtualkeyboard_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequick.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequick_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginequickdelegatesqml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webview.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webviewquick.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_webviewquick_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_xml.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\qt_functions.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\qt_config.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\win32-msvc\qmake.conf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\exclusive_builds.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\common\msvc-version.conf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\toolchain.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\default_pre.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\win32\default_pre.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\resolve_config.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\exclusive_builds_post.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\default_post.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\qml_debug.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\entrypoint.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\precompile_header.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\warn_on.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\qmake_use.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\file_copies.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\win32\windows.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\testcase_targets.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\exceptions.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\yacc.prf:
..\..\..\ruanjian\Qt\6.3.1\msvc2019_64\mkspecs\features\lex.prf:
TheSteambird.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile TheSteambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-steambird-qmake_all FORCE

make_first: sub-steambird-make_first  FORCE
all: sub-steambird-all  FORCE
clean: sub-steambird-clean  FORCE
distclean: sub-steambird-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-steambird-install_subtargets FORCE
uninstall_subtargets: sub-steambird-uninstall_subtargets FORCE

sub-steambird-debug:
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile debug
debug: sub-steambird-debug

sub-steambird-release:
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile release
release: sub-steambird-release

sub-steambird-check:
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-steambird-check

sub-steambird-benchmark:
	@if not exist steambird\ mkdir steambird\ & if not exist steambird\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd steambird\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\code\TheSteambird\TheSteambird\steambird\steambird.pro -spec win32-msvc "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-steambird-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

